# configurations
# 详情请参考：https://halo.run/develop/theme.html#settings-yaml
genernal:
  label: 基本设置
  items:
    home_title:
      name: home_title
      label: 首页展示博客名
      type: text
      placeholder: '用于首页展示名字'
    home_description:
      name: home_description
      label: 首页描述
      type: text
      placeholder: '用于首页描述'
    home_cover:
      name: home_cover
      label: 首页背景
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq42tnu3vj31870u0wqe.jpg
    header_logoimg:
      name: header_logoimg
      label: 菜单logo
      type: attachment
    header_logo_height:
      name: header_logo_height
      label: 菜单logo高度
      type: text
      placeholder: '比如: 20px'
    auto_night_mode:
      name: auto_night_mode
      label: 暗夜模式总开关
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    night_mode:
      name: night_mode
      label: 暗夜模式顶部按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    top_search:
      name: top_search
      label: 搜索
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_summary:
      name: post_summary
      label: 首页文章摘要
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    Icp:
      name: Icp
      label: 'ICP备案号'
      type: text
      placeholder: '填入ICP备案号，没有则不填'
    PublicSecurityRecord:
      name: PublicSecurityRecord
      label: '网安备案号'
      type: text
      placeholder: '填入网安备案号代码，没有则不填'
    QR_code_zfb:
      name: QR_code_zfb
      label: '支付宝二维码链接'
      type: attachment
      placeholder: '支付宝收款二维码链接，不填不显示'
    QR_code_wx:
      name: QR_code_wx
      label: '微信二维码链接'
      type: attachment
      placeholder: '微信收款二维码链接，不填不显示'
head_img:
  label: 网页首部图片
  items:
    archives_patternimg:
      name: archives_patternimg
      label: 归档页面头部装饰图
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq2gdqaigj31jk0tl7wi.jpg
    links_patternimg:
      name: links_patternimg
      label: 友情链接页面头部装饰图
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq2gdqaigj31jk0tl7wi.jpg
    tag_patternimg:
      name: tag_patternimg
      label: 标签页面头部装饰图
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq2gdqaigj31jk0tl7wi.jpg
    categories_patternimg:
      name: categories_patternimg
      label: 分类页面头部装饰图
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq2gdqaigj31jk0tl7wi.jpg
    journals_patternimg:
      name: journals_patternimg
      label: 日志下文章页面头部装饰图
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq2gdqaigj31jk0tl7wi.jpg
    links_placeholder:
      name: links_placeholder
      label: 友情链接默认用户头像
      type: attachment
      default: https://tva1.sinaimg.cn/large/0082zybply1gbq3zi6efej30t70t50wh.jpg
post:
  label: 文章页
  items:
    post_toc:
      name: post_toc
      label: 目录
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_nepre:
      name: post_nepre
      label: 下一篇
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
custom:
  label: 自定义
  items:
    TimeStatistics:
      name: TimeStatistics
      label: '站点运行时间统计'
      type: text
      placeholder: '填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00'
    Custom_css_src:
      name: Custom_css_src
      label: '自定义外部css文件链接'
      type: text
      placeholder: '填入css文件链接，不需要style标签'
    Custom_css:
      name: Custom_css
      label: '自定义css代码'
      type: textarea
      placeholder: '写入css代码，不需要style标签'
    Custom_js_head:
      name: Custom_js_head
      label: 'head结束标签前自定义js代码'
      type: textarea
      placeholder: '写入js代码，不需要script标签'
    Custom_js_foot_src:
      name: Custom_js_foot_src
      label: 'body结束标签前自定义外部js文件链接'
      type: text
      placeholder: '填入js文件链接，需要script标签'
    Custom_js_foot:
      name: Custom_js_foot
      label: 'body结束标签前自定义js代码'
      type: textarea
      placeholder: '写入js代码，不需要script标签'
title:
  label: 页面标题
  items:
    links_title:
      name: links_title
      label: 友链页面标题
      type: text
      default: 友链
    jounarls_title:
      name: jounarls_title
      label: 日志页面标题
      type: text
      default: 日志
    tags_title:
      name: tags_title
      label: 标签页面标题
      type: text
      default: 标签列表
    categories_title:
      name: categories_title
      label: 分类列表页面标题
      type: text
      default: 分类列表
    achieve_title:
      name: achieve_title
      label: 归档页面标题
      type: text
      default: 归档
social:
  label: 社交网络
  items:
    #    wechat:
    #      name: wechat
    #      label: 微信二维码
    #      type: attachment
    sina:
      name: sina
      label: 新浪微博
      type: text
    qq:
      name: qq
      label: 腾讯QQ
      type: text
    github:
      name: github
      label: Github 名
      type: text
    zhihu:
      name: zhihu
      label: 知乎
      type: text
    mail:
      name: mail
      label: 邮箱
      type: text
